//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR3.Resource.Model
{
    using System;
    using System.Collections.Generic;
    using System.Drawing;

    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.ClientService = new HashSet<ClientService>();
        }
        public string GetBackground(double discount)
        {
            if (discount > 0) return "#e7fabf";
            else return "#fff";
        }
        public bool GetDiscount(double discount)
        {
            if (discount > 0) return true;
            else return false;
        }

        public int ID { get; set; }
        public string Title { get; set; }
        public int Cost { get; set; }
        public int DurationInMinuts { get; set; }
        public Nullable<double> Discount { get; set; }
        public string MainImagePath { get; set; }
        public string Background => GetBackground(Discount.Value);
        public string Image => "/Resource/" + MainImagePath;
        public bool CheckDis => GetDiscount(Discount.Value);
        public double CostDis => Cost - Cost * Discount.Value;
        public string Sale => $"* скидка {Discount.Value * 100}%";
  
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientService { get; set; }
    }
}
